1657782698854	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1657782838279	Sync.Service	DEBUG	User-Agent: Firefox/102.0.1 (Linux x86_64) FxSync/1.104.0.20220706125320.desktop
1657782838279	Sync.Service	INFO	Starting sync at 2022-07-14 12:43:58 in browser session K413WVAkpR6v
1657782838279	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1657782838280	Sync.Status	INFO	Resetting Status.
1657782838280	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1657782838280	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1657782838280	FirefoxAccounts	DEBUG	getOAuthToken enter
1657782838280	FirefoxAccounts	TRACE	getCachedToken returning cached token
1657782838280	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1657782838281	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1657782838320	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2153390067 - 
1657782838321	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"<no message>\"  nsresult: \"0x805a1ff3 (<unknown>)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1657782838321	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1657782838321	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1657782838322	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1657782838323	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
