1649744732389	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649744864047	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1649744864048	Sync.Service	DEBUG	User-Agent: Firefox/99.0 (Linux x86_64) FxSync/1.101.0.20220404170724.desktop
1649744864048	Sync.Service	INFO	Starting sync at 2022-04-12 11:57:44 in browser session _RXckoDlmblV
1649744864048	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649744864052	Sync.Status	INFO	Resetting Status.
1649744864052	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1649744864052	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649744864052	FirefoxAccounts	DEBUG	getOAuthToken enter
1649744864053	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649744864053	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649744864054	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649744955503	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1649744955503	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649744955504	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649744955505	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649744955581	Sync.SyncScheduler	DEBUG	Woke from sleep.
1649744955582	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1649744955582	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1649744955582	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649744957114	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1649744957114	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649744957582	Sync.Service	DEBUG	User-Agent: Firefox/99.0 (Linux x86_64) FxSync/1.101.0.20220404170724.desktop
1649744957582	Sync.Service	INFO	Starting sync at 2022-04-12 11:59:17 in browser session _RXckoDlmblV
1649744957583	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:62:5) JS Stack trace: LockException@util.js:62:5
throwLockException@util.js:148:11
WrappedLock@util.js:162:15
_lockedSync@service.js:1370:6
sync/<@service.js:1334:18
WrappedCatch@util.js:133:27
sync@service.js:1335:7
1649744957583	Sync.Service	INFO	Cannot start sync: already syncing?
1649744961572	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649744963587	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1649744963587	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1649744963590	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649744963591	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649744963593	Sync.Service	DEBUG	User-Agent: Firefox/99.0 (Linux x86_64) FxSync/1.101.0.20220404170724.desktop
1649744963593	Sync.Service	INFO	Starting sync at 2022-04-12 11:59:23 in browser session _RXckoDlmblV
1649744963593	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:62:5) JS Stack trace: LockException@util.js:62:5
throwLockException@util.js:148:11
WrappedLock@util.js:162:15
_lockedSync@service.js:1370:6
sync/<@service.js:1334:18
WrappedCatch@util.js:133:27
sync@service.js:1335:7
1649744963593	Sync.Service	INFO	Cannot start sync: already syncing?
1649744964505	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1649744964506	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1649744964506	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1649744964508	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
